pipeline:
  login:
    image: ubox/awscli
    commands:
      - export login_string=`aws ecr get-login --no-include-email --region us-east-1`
  build_app:
    image: plugins/ecr
    repo: 153804614251.dkr.ecr.us-east-1.amazonaws.com/ecr-demo
    registry: 153804614251.dkr.ecr.us-east-1.amazonaws.com
    region: us-east-1
  build_api:
    image: plugins/ecr
    repo: 153804614251.dkr.ecr.us-east-1.amazonaws.com/ecr-demo-api
    registry: 153804614251.dkr.ecr.us-east-1.amazonaws.com
    region: us-east-1
    dockerfile: Dockerfile.api
  deploy:
    image: docker
    commands:
      - eval $login_string
      - docker pull 153804614251.dkr.ecr.us-east-1.amazonaws.com/ecr-demo
      - docker pull 153804614251.dkr.ecr.us-east-1.amazonaws.com/ecr-demo-api
      - docker stack deploy -c app.yml test
      - docker stack deploy -c api.yml test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
