pipeline:
#   create_repo:
#     image: ubox/awscli
#     commands:
#       - export AWS_DEFAULT_REGION=us-east-1
#       - aws ecr create-repository --repository-name ecr-demo
  build:
    image: plugins/ecr
    repo: 153804614251.dkr.ecr.us-east-1.amazonaws.com/ecr-demo
    registry: 153804614251.dkr.ecr.us-east-1.amazonaws.com
    region: us-east-1
  deploy:
    image: docker
    commands:
      - docker stack deploy -c nginx.yml test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
