version: '3.5'

services:
  api:
    image: 153804614251.dkr.ecr.us-east-1.amazonaws.com/ecr-demo-api:"${DRONE_COMMIT_SHA:0:8}"
    networks:
      - appnet
    deploy:
      replicas: 1
      labels:
        - traefik.port=80
        - traefik.frontend.passHostHeader=true
        - traefik.frontend.rule=Host:uptest.treehub.me;PathPrefix:/api
        - traefik.frontend.headers.SSLRedirect=true
        - traefik.docker.network=appnet

networks:
  appnet:
    external: true
