version: '3.5'

services:
  app:
    image: 153804614251.dkr.ecr.us-east-1.amazonaws.com/ecr-demo
    networks:
      - appnet
    deploy:
      replicas: 2
      labels:
        - traefik.port=80
        - traefik.frontend.passHostHeader=true
        - traefik.frontend.rule=Host:uptest.treehub.me
        - traefik.frontend.headers.SSLRedirect=true
        - traefik.docker.network=appnet

networks:
  appnet:
    external: true
