version: '3.5'

services:
  nginx-test:
    image: 153804614251.dkr.ecr.us-east-1.amazonaws.com/ecr-demo
    networks:
      - appnet
    deploy:
      replicas: 2
      labels:
        - traefik.port=80
networks:
  appnet:
    external: true
